name: GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run build
        uses: area44/workflows/astro@v3.2.0
